name: 'my_energy_project'
# while you need to name a profile, you do not need to have a profiles.yml file defined when using Cosmos
profile: my_profile
models:
  my_energy_project:
    materialized: table
# create a variable called country_code and give it the default value "FR" (for France)
vars:
  country_code: "FR"